# Generated by Django 6.0.4 on 2026-04-19 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room_Booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupieddate',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupied_dates', to='Room_Booking.room'),
        ),
    ]
