# Generated by Django 6.0.4 on 2026-05-02 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room_Booking', '0002_alter_occupieddate_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupieddate',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupiedDates', to='Room_Booking.room'),
        ),
    ]
